
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dbuser
  password: dbpass
  host: localhost

development:
  <<: *default
  database: tasklist_development

test:
  <<: *default
  database: tasklist_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: tasklist_production
  username: tasklist
  password: <%= ENV['TASKLIST_DATABASE_PASSWORD'] %>
